---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Verify webserver is running
    uri:
      url: https://localhost:8443/admin
      validate_certs: false
    register: result
  
  - name: Assert that status code is 200
    assert:
      that:
        - result.status == 200